### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by nsputnik** [ffd8/xyscope#4]
With the xtra_video.pde example script I am getting an error "UnsatisfiedLinkError: no opencv_java245 in java.library.path" and then it lists the path to Processing.app/Contents/Java/core/library/macos-x86_64 and paths at documents/Processing/libraries to minim, video, and opencv_processing library directories.  Running Mac OSX 10.14 Intel, getting the same error on 12.3 Apple Silicone.

**Comment by ffd8** [comment]
@nsputnik I did some research on this, since it seems to be an issue with the 'OpenCV for Processing' and MacOS's new 64bit requirement and found [this discussion on the opencv lib](https://github.com/atduskgreg/opencv-processing/issues/121) which points to [this solution](https://discourse.processing.org/t/opencv-error-in-processing-4-0b2/33284/7) from the processing forum. 
Let me know if that solves it (also in one or both setups).

EDIT: just saw you also posted on the repo issues above.. hmm will also check getting it working on my new setup (apple silicon + 12.5)

**Comment by ffd8** [comment]
@nsputnik found a solution for my setup (MBP M1+, 12.5.x)
- ([download processing 4.0.1 MacOs (Intel 64-bit)](https://github.com/processing/processing4/releases/download/processing-1286-4.0.1/processing-4.0.1-macos-x64.zip))
- open once (need to allow macos security warnings)
- quit
- manually install [@jaegonlee opencv for processing update for 4.0](https://github.com/jaegonlee/opencv-processing/releases/tag/0.6)
- CTRL + Click Processing app and 'Show package contents'
- browse to: `Contents / Java / core / library / macos-x86_64`
- copy into this dir the `libopencv_java400.dylib` file that came with [@jaegonlee update for 4.0](https://github.com/jaegonlee/opencv-processing/releases/tag/0.6), as suggested by [@kkirklewski on the forum](https://discourse.processing.org/t/opencv-error-in-processing-4-0b2/33284/8)
- reopen Processing and test an example for OpenCV

This worked fine for me using the Intel x86 build even though I'm on apple silicon. The first time I ran it, it warned that OpenCV isn't made for my hardware or something like that but ran.. now having quit and reopen, no more warning.. just works.

Unfortunately I can't figure out how to get it installed and working on Processing's [Apple Silicon](https://github.com/processing/processing4/releases/download/processing-1286-4.0.1/processing-4.0.1-macos-aarch64.zip) release... something I notice deep within Processing's package contents, `Contents / Java / core / library /` is a folder called `macos-aarch64` (obviously for apple silicon ref), however the OpenCV lib doesn't have that folder.. only one called 'macosx64'.. tried manually created a folder to match the style for `aarch` but can't get it to find the link.. will make a post on the [opencv issue](https://github.com/atduskgreg/opencv-processing/issues/121) to see if someone has given it a try since the stable releases for both hardware.

**Comment by nsputnik** [comment]
@ffd8 That you so much.
So I opened Processing today and noticed there was an update for opencv-processing.  I figured I would try running the update before following all of your instructions and run the script again.  It is working!  (X68 10.14).  I don't know if commenting on the issue in the project prompted this but all seems good now.  I'll try on Apple Silicon too and let you know the results.  I think for the most part Rosetta 2 should help any X86 code on Apple Silicon, it's just not native code I guess.

**Comment by ffd8** [comment]
@nsputnik Aha - awesome, also just did the same on latest processing with apple silicon = works just fine! 
I see [the issue](https://github.com/atduskgreg/opencv-processing/issues/122) as the latest dev was started in a [new repo](https://github.com/cansik/opencv-processing) that wasn't linked to the original. Updating the lib within Processing now links to that new repo and hopefully a note will be added to the original readme pointing folks there.

**Comment by ffd8** [comment]
FYI, the `xtra_video` XYscope demo works fine in the x86 environment, but fails on apple silicon due to a [gstreamer issue for the video library](https://github.com/processing/processing-video/issues/199) which is currently being worked on.
